<?xml version="1.0" encoding="utf-8"?><Database Name="CookBook" EntityNamespace="CookBook.DataLayer" ContextNamespace="CookBook.DataLayer" Class="LinqToSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\mssqllocaldb;Initial Catalog=CookBook;Integrated Security=True;Pooling=False" SettingsObjectName="CookBook.Properties.Settings" SettingsPropertyName="CookBookConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="EnergyValue" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Protein" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Fats" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Carbs" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Association Name="Product_ProductsToType" Member="ProductsToTypes" ThisKey="Id" OtherKey="ProductId" Type="ProductsToType" />
      <Association Name="Product_ProductUnit" Member="ProductUnits" ThisKey="Id" OtherKey="ProductId" Type="ProductUnit" />
    </Type>
  </Table>
  <Table Name="dbo.ProductTypes" Member="ProductTypes">
    <Type Name="ProductType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ProductType_ProductsToType" Member="ProductsToTypes" ThisKey="Id" OtherKey="TypeId" Type="ProductsToType" />
    </Type>
  </Table>
  <Table Name="dbo.ProductsToTypes" Member="ProductsToTypes">
    <Type Name="ProductsToType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_ProductsToType" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" />
      <Association Name="ProductType_ProductsToType" Member="ProductType" ThisKey="TypeId" OtherKey="Id" Type="ProductType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductUnit" Member="ProductUnits">
    <Type Name="ProductUnit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mass" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Association Name="ProductUnit_Ingredient" Member="Ingredients" ThisKey="Id" OtherKey="ProductUnitId" Type="Ingredient" />
      <Association Name="Product_ProductUnit" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ingredients" Member="Ingredients">
    <Type Name="Ingredient">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductUnitId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="RecipeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ProductUnit_Ingredient" Member="ProductUnit" ThisKey="ProductUnitId" OtherKey="Id" Type="ProductUnit" IsForeignKey="true" />
      <Association Name="Recipe_Ingredient" Member="Recipe" ThisKey="RecipeId" OtherKey="Id" Type="Recipe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Recipes" Member="Recipes">
    <Type Name="Recipe">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CookingTime" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="PortionCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CookingMethod" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Recipe_Ingredient" Member="Ingredients" ThisKey="Id" OtherKey="RecipeId" Type="Ingredient" />
      <Association Name="Recipe_RecipesToType" Member="RecipesToTypes" ThisKey="Id" OtherKey="RecipeId" Type="RecipesToType" />
    </Type>
  </Table>
  <Table Name="dbo.DishTypes" Member="DishTypes">
    <Type Name="DishType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="DishType_RecipesToType" Member="RecipesToTypes" ThisKey="Id" OtherKey="TypeId" Type="RecipesToType" />
    </Type>
  </Table>
  <Table Name="dbo.RecipesToTypes" Member="RecipesToTypes">
    <Type Name="RecipesToType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RecipeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DishType_RecipesToType" Member="DishType" ThisKey="TypeId" OtherKey="Id" Type="DishType" IsForeignKey="true" />
      <Association Name="Recipe_RecipesToType" Member="Recipe" ThisKey="RecipeId" OtherKey="Id" Type="Recipe" IsForeignKey="true" />
    </Type>
  </Table>
</Database>